project:
  type: website
  output-dir: docs

website:
  title: "NGUYEN HUU KIEN"
  navbar:
    right:
      - about.qmd
      - text: "Language"
        menu:
          - text: "English"
            href: index.qmd
          - text: "Tiếng Việt"
            href: index-vi.qmd
          - text: "中文"
            href: index-zh.qmd
      - icon: github
        href: https://github.com/kienngynh
      - icon: linkedin
        href: https://linkedin.com/in/kienbk60

format:
  html:
    theme: cosmo
    css: styles.css
