project:
  type: website
  output-dir: docs

website:
  title: "NGUYEN HUU KIEN"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kienngynh
      - icon: linkedin
        href: https://linkedin.com/in/kienbk60

format:
  html:
    theme: cosmo
    css: styles.css
